### ISSUE TITLE
DSC "Reasons" needs prefix

### ISSUE THREAD

**Issue by Jaykul** [anypackage/dsc#12]
Sorry for the drive-by issue, but basically, we can't use [Reasons] because if everyone does it, it breaks DSC. 

https://github.com/dsccommunity/DscResource.Base/issues/4

This is **Microsoft's fault**, but their approach so far is to just tell you to use a different name: 
https://learn.microsoft.com/en-us/powershell/dsc/concepts/resources?view=dsc-3.0#embedding-classes

It seems obvious (to me) that they should just expose a [Reasons] class themselves (or just use a PSObject), but whatever.
One way to fix it is to just rename the class. Another way would be to follow this example:
https://github.com/dsccommunity/DscResource.Base/pull/10

**Comment by ThomasNieto** [comment]
@Jaykul thanks for the info. I'll get a fix out.

**Comment by ThomasNieto** [comment]
@Jaykul v0.1.1 has been published with this fix.
